### ISSUE TITLE
openFortiGUI crashed / the application is already running

### ISSUE THREAD

**Issue by kevinherron** [theinvisible/openfortigui#45] opened 2018-06-30 20:21 UTC
So... I often come back to my desktop to find that openFortiGUI has crashed and the Ubuntu 18.04 crash reporter wants to send off the crash dump or whatever... fine. I then tell it not to re-open the application.

The problem is... this leaves the openFortiGUI process in a "defunct" zombie state, and subsequent attempts to open the application give me an error dialog saying it's already running.

The only way to escape this is to log out or restart because the zombie process parent is pid 0.

```
kevin@kevin-wx:~$ ps aux | grep openforti
kevin      402  0.0  0.0  21536  1032 pts/2    S+   13:19   0:00 grep --color=auto openforti
kevin     4714  0.0  0.0      0     0 tty2     Z+   Jun29   0:05 [openfortigui] <defunct>
```

**Comment by kevinherron** [comment] 2018-06-30 22:33
For now I've built my own version that displays only a warning and does not exit :smile:

**Comment by theinvisible** [comment] 2018-07-08 09:40
Hi,

thanks for your report.

Maybe you can do some debugging and so help me to find the cause for the crash.

For details see https://hadler.me/linux/openfortigui/ -> Debugging

Thanks
Rene

**Comment by theinvisible** [comment] 2018-09-02 13:44
Closing this issue, if there are some more information can open it again.

**Closed by theinvisible** 2018-09-02 13:44 UTC
