### ISSUE TITLE
Use sudo in .desktop entry

### ISSUE THREAD

**Issue by Seb-Solon** [theinvisible/openfortigui#42] opened 2018-06-08 14:47 UTC
Hi there,

The desktop file simply run the binary as written here  : https://github.com/theinvisible/openfortigui/blob/master/openfortigui/app-entry/openfortigui.desktop#L6 
The default setup (with packaging) adds /usr/bin/openfortigui for members of sudo group without password in sudoers, however if we don't launch it with such privileges VPN connections will not work. 

What do you think about adding /usr/bin/sudo to the exec line? 

Another option could be editing the sudoers again to allow /usr/sbin/pppd as openfortigui spawn a pppd process in the end. But it may not be enough. 

Let me know if you think it's a good option.

Regards,

EDIT : Doing this will break the Password manager integration feature as gnome-keyring and kde wallet are not run in the same user. I am not sure what is the best option here :disappointed:

**Comment by Seb-Solon** [comment] 2018-06-08 15:49
Hum strange, 

After playing a bit around with sudo option, the desktop file works with the initial exec line. I am not sure if it is necessary then (which surprised me at the beginning).

Feel free to close this if you think it is not relevant in the end.

**Comment by theinvisible** [comment] 2018-06-09 18:55
Hi,

thanks for your request.

OpenFortiGUI was designed to run as less as possible in privileged (root) mode.

It is not good security wise to run a GUI as root if not absolutely required. The VPN process on the other side needs root privileges to interact with the system. This is also required for openfortivpn. So it was split to use superuser privileges only when required.

As you said it will also break some other desktop related things because its simply run with the wrong user and so desktop integration is more difficult.

So i will close this but still thanks for your request.

Regards
Rene

**Closed by theinvisible** 2018-06-09 18:55 UTC

**Comment by ibrahima** [comment] 2018-12-07 18:18
Hmm, is it supposed to prompt for sudo password via gui when trying to connect? At least for me, it doesn't work unless I start it from a terminal so that I can enter my sudo password when prompted, but I'd prefer not to have to leave a terminal running with that open.

Thanks!

**Comment by angela-d** [comment] 2018-12-20 02:42
@ibrahima You can launch OpenFortiGUI with sudo by doing the following (starting at **Get rid of the password prompt**): https://github.com/angela-d/brain-dump/blob/master/sysadmin/fortiguard-vpn-linux.md

This way you're only launching OpenFortiGUI and nothing else with elevated permissions.

If you did not set the connection up originally under sudo permissions, it may break the integration as the passcode would be assigned to another 'user.'  In that case, just delete the connection config and re-add it after this tweak.
